# Generated by Django 5.1.1 on 2024-11-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cor_do_carro',
            field=models.CharField(default='Desconhecida', max_length=50),
        ),
    ]
