# Generated by Django 5.1.1 on 2024-11-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_cor_do_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cor_do_carro',
        ),
    ]
